#!/usr/bin/env bats

setup() {
    REPO_ROOT="$(cd "$BATS_TEST_DIRNAME/.." && pwd)"
}

@test "bundle generator builds a self-contained script" {
    run "$REPO_ROOT/tools/build-rootavd-bundle.sh"

    [ "$status" -eq 0 ]
    [ -x "$REPO_ROOT/dist/rootAVD.sh" ]

    run bash -n "$REPO_ROOT/dist/rootAVD.sh"
    [ "$status" -eq 0 ]

    run sh -n "$REPO_ROOT/dist/rootAVD.sh"
    [ "$status" -eq 0 ]
}

@test "bundle generator writes release metadata and bundled mode flag" {
    "$REPO_ROOT/tools/build-rootavd-bundle.sh" > /dev/null

    run bash -c '
    bundle="$1"
    missing=0

    while IFS= read -r required_text; do
      [ -n "$required_text" ] || continue
      if ! grep -F -- "$required_text" "$bundle" > /dev/null; then
        printf "missing bundle metadata: %s\n" "$required_text"
        missing=1
      fi
    done << REQUIRED_BUNDLE_METADATA
Generated rootAVD single-file bundle.
Do not edit this file directly; edit rootAVD.sh and lib/rootavd/*.sh instead.
ROOTAVD_BUNDLED=true
BEGIN rootAVD.sh loader
REQUIRED_BUNDLE_METADATA

    exit "$missing"
  ' _ "$REPO_ROOT/dist/rootAVD.sh"

    [ "$status" -eq 0 ]
    [ "$output" = "" ]
}

@test "bundle generator keeps only generated-file ShellCheck suppressions at bundle scope" {
    "$REPO_ROOT/tools/build-rootavd-bundle.sh" > /dev/null

    run bash -c '
    bundle="$1"

    header=$(grep -F "# shellcheck disable=" "$bundle" | head -n 1)
    case "$header" in
      *SC1091*|*SC2088*)
        printf "unexpected bundle-wide suppression: %s\n" "$header"
        exit 1
        ;;
    esac

    printf "%s\n" "$header"
  ' _ "$REPO_ROOT/dist/rootAVD.sh"

    [ "$status" -eq 0 ]
    [ "$output" = "# shellcheck disable=SC1078,SC1079,SC2004,SC2027,SC2034,SC2140" ]
}

@test "bundle includes every module loaded by source mode" {
    "$REPO_ROOT/tools/build-rootavd-bundle.sh" > /dev/null

    run bash -c '
    source "$1" SOURCING >/dev/null
    missing=0

    if ! grep -F "BEGIN lib/rootavd/bootstrap.sh" "$2" > /dev/null; then
      printf "%s\n" "missing bundled module: bootstrap.sh"
      missing=1
    fi

    while IFS= read -r module; do
      [ -n "$module" ] || continue
      if ! grep -F "BEGIN lib/rootavd/$module" "$2" > /dev/null; then
        printf "missing bundled module: %s\n" "$module"
        missing=1
      fi
    done << ROOTAVD_MODULES
$(rootavd_module_files)
ROOTAVD_MODULES

    exit "$missing"
  ' _ "$REPO_ROOT/rootAVD.sh" "$REPO_ROOT/dist/rootAVD.sh"

    [ "$status" -eq 0 ]
    [ "$output" = "" ]
}

@test "source loader exposes source-mode internal defaults" {
    run bash -c '
    source "$1" SOURCING
    printf "BUNDLED=%s\nLIB=%s\nMAIN=%s\nLOADER=%s\n" \
      "$ROOTAVD_BUNDLED" \
      "$ROOTAVD_LIB_DIR" \
      "$(type -t rootavd_main)" \
      "$(type -t rootavd_load_modules)"
  ' _ "$REPO_ROOT/rootAVD.sh"

    [ "$status" -eq 0 ]
    [ "${lines[0]}" = "BUNDLED=false" ]
    [ "${lines[1]}" = "LIB=$REPO_ROOT/lib/rootavd" ]
    [ "${lines[2]}" = "MAIN=function" ]
    [ "${lines[3]}" = "LOADER=function" ]
}

@test "entrypoint calls rootavd_main only at loader boundary" {
    run grep -R -n 'rootavd_main[[:space:]]*"\$@"' "$REPO_ROOT/rootAVD.sh" "$REPO_ROOT/lib/rootavd"

    [ "$status" -eq 0 ]
    [ "$output" = "$REPO_ROOT/rootAVD.sh:27:rootavd_main \"\$@\"" ]
}

@test "bundled script preserves sourced argument parsing" {
    "$REPO_ROOT/tools/build-rootavd-bundle.sh" > /dev/null

    run bash -c 'source "$1" SOURCING DEBUG; printf "%s\n" "$DEBUG"' _ "$REPO_ROOT/dist/rootAVD.sh"

    [ "$status" -eq 0 ]
    [ "$output" = "true" ]
}

@test "bundled script preserves nounset-safe sourced argument parsing" {
    "$REPO_ROOT/tools/build-rootavd-bundle.sh" > /dev/null

    run bash -u -c 'source "$1" SOURCING; printf "%s %s\n" "$SOURCING" "$restore"' _ "$REPO_ROOT/dist/rootAVD.sh"

    [ "$status" -eq 0 ]
    [ "$output" = "true false" ]
}

@test "bundled script preserves all public argument parsing" {
    "$REPO_ROOT/tools/build-rootavd-bundle.sh" > /dev/null

    run bash -c '
    SOURCING=true source "$1" \
      "system-images/android-36/google_apis_playstore/x86_64/ramdisk.img" \
      PATCHFSTAB GetUSBHPmodZ ListAllAVDs InstallApps UpdateBusyBoxScript \
      AddRCscripts toggleRamdisk FAKEBOOTIMG
    printf "%s\n" \
      "$PATCHFSTAB" \
      "$GetUSBHPmodZ" \
      "$ListAllAVDs" \
      "$InstallApps" \
      "$UpdateBusyBoxScript" \
      "$AddRCscripts" \
      "$toggleRamdisk" \
      "$FAKEBOOTIMG" \
      "$RAMDISKIMG"
  ' _ "$REPO_ROOT/dist/rootAVD.sh"

    [ "$status" -eq 0 ]
    [ "${lines[0]}" = "true" ]
    [ "${lines[1]}" = "true" ]
    [ "${lines[2]}" = "true" ]
    [ "${lines[3]}" = "true" ]
    [ "${lines[4]}" = "true" ]
    [ "${lines[5]}" = "true" ]
    [ "${lines[6]}" = "true" ]
    [ "${lines[7]}" = "true" ]
    [ "${lines[8]}" = "true" ]

    run bash -c 'SOURCING=true source "$1" ramdisk.img restore; printf "%s\n" "$restore"' _ "$REPO_ROOT/dist/rootAVD.sh"
    [ "$status" -eq 0 ]
    [ "$output" = "true" ]

    run bash -c 'SOURCING=true source "$1" ramdisk.img InstallKernelModules; printf "%s\n" "$InstallKernelModules"' _ "$REPO_ROOT/dist/rootAVD.sh"
    [ "$status" -eq 0 ]
    [ "$output" = "true" ]

    run bash -c 'SOURCING=true source "$1" ramdisk.img InstallPrebuiltKernelModules; printf "%s\n" "$InstallPrebuiltKernelModules"' _ "$REPO_ROOT/dist/rootAVD.sh"
    [ "$status" -eq 0 ]
    [ "$output" = "true" ]
}

@test "bundled script is self-contained when copied without modules" {
    "$REPO_ROOT/tools/build-rootavd-bundle.sh" > /dev/null
    bundle_dir="$BATS_TEST_TMPDIR/bundle-only"
    mkdir -p "$bundle_dir"
    cp "$REPO_ROOT/dist/rootAVD.sh" "$bundle_dir/rootAVD.sh"

    run bash -c 'source "$1" SOURCING DEBUG; printf "%s\n" "$DEBUG"' _ "$bundle_dir/rootAVD.sh"

    [ "$status" -eq 0 ]
    [ "$output" = "true" ]
}

@test "bundled script runs through sh without source modules" {
    "$REPO_ROOT/tools/build-rootavd-bundle.sh" > /dev/null
    bundle_dir="$BATS_TEST_TMPDIR/sh bundle only"
    mkdir -p "$bundle_dir"
    cp "$REPO_ROOT/dist/rootAVD.sh" "$bundle_dir/rootAVD.sh"

    run sh "$bundle_dir/rootAVD.sh" SOURCING DEBUG

    [ "$status" -eq 0 ]
    [[ "$output" != *"Missing rootAVD"* ]]
}

@test "bundle generator refuses modules with top-level execution" {
    work="$BATS_TEST_TMPDIR/reject top level execution"
    mkdir -p "$work"
    cp "$REPO_ROOT/rootAVD.sh" "$work/rootAVD.sh"
    cp -R "$REPO_ROOT/lib" "$work/lib"
    cp -R "$REPO_ROOT/tools" "$work/tools"
    printf '%s\n' 'rootavd_main "$@"' >> "$work/lib/rootavd/log.sh"

    run "$work/tools/build-rootavd-bundle.sh"

    [ "$status" -eq 1 ]
    [[ "$output" == *"Refusing to bundle module with top-level execution"* ]]
}

@test "bundle generator refuses indented module top-level execution" {
    work="$BATS_TEST_TMPDIR/reject indented top level execution"
    mkdir -p "$work"
    cp "$REPO_ROOT/rootAVD.sh" "$work/rootAVD.sh"
    cp -R "$REPO_ROOT/lib" "$work/lib"
    cp -R "$REPO_ROOT/tools" "$work/tools"
    printf '%s\n' '    CopyMagiskToAVD "$@"' >> "$work/lib/rootavd/log.sh"

    run "$work/tools/build-rootavd-bundle.sh"

    [ "$status" -eq 1 ]
    [[ "$output" == *"Refusing to bundle module with top-level execution"* ]]
}
