# shellcheck shell=bash

ShowHelpText() {
    bold=$(tput bold)
    normal=$(tput sgr0)
    echo "${bold}rootAVD A Script to root AVD by NewBit XDA${normal}"
    echo ""
    echo "Usage:	${bold}rootAVD [DIR/ramdisk.img] [OPTIONS] | [EXTRA ARGUMENTS]${normal}"
    echo "or:	${bold}rootAVD [ARGUMENTS]${normal}"
    echo ""
    echo "Arguments:"
    echo "	${bold}ListAllAVDs${normal}			Lists Command Examples for ALL installed AVDs"
    echo ""
    echo "	${bold}InstallApps${normal}			Just install all APKs placed in the Apps folder"
    echo ""
    echo "Main operation mode:"
    echo "	${bold}DIR${normal}				a path to an AVD system-image"
    echo "					- must always be the ${bold}1st${normal} Argument after rootAVD"
    echo "	"
    echo "ADB Path | Ramdisk DIR | ANDROID_HOME:"
    echo "	${bold}[M]ac/Darwin:${normal}			export PATH=${defaultHOME_M:-~/Library/Android/sdk}/platform-tools:\$PATH"
    echo "					export PATH=\$ANDROID_HOME/platform-tools:\$PATH"
    echo "					system-images/android-\$API/google_apis_playstore/x86_64/"
    echo "	"
    echo "	${bold}[L]inux:${normal}			export PATH=${defaultHOME_L:-~/Android/Sdk}/platform-tools:\$PATH"
    echo "					export PATH=\$ANDROID_HOME/platform-tools:\$PATH"
    echo "					system-images/android-\$API/google_apis_playstore/x86_64/"
    echo "	"
    echo "	${bold}[W]indows:${normal}			set PATH=%LOCALAPPDATA%\Android\Sdk\platform-tools;%PATH%"
    echo "					set PATH=%ANDROID_HOME%\platform-tools;%PATH%"
    printf '%s\n' "					system-images\android-\$API\google_apis_playstore\x86_64\\"
    echo "	"
    echo "	${bold}ANDROID_HOME:${normal}			By default, the script uses ${bold}${defaultHOME:-~/Library/Android/sdk}${normal}, to set its Android Home"
    echo "					directory, search for AVD system-images and ADB binarys. This behaviour"
    echo "					can be overwritten by setting the ANDROID_HOME variable."
    echo "					e.g. ${bold}export ANDROID_HOME=~/Downloads/sdk${normal}"
    echo "	"
    echo "	${bold}\$API:${normal}				25,29,30,31,32,33,34,35,36,36.1,etc."
    echo "	"
    echo "Options:"
    echo "	${bold}restore${normal}				restore all existing ${bold}.backup${normal} files, but doesn't delete them"
    echo "					- the AVD doesn't need to be running"
    echo "					- no other Argument after will be processed"
    echo "	"
    echo "	${bold}InstallKernelModules${normal}		install ${bold}custom build kernel and its modules${normal} into ramdisk.img"
    echo "					- kernel (bzImage) and its modules (initramfs.img) are inside rootAVD"
    echo "					- both files will be deleted after installation"
    echo "	"
    echo "	${bold}InstallPrebuiltKernelModules${normal}	download and install an ${bold}AOSP prebuilt kernel and its modules${normal} into ramdisk.img"
    echo "					- similar to ${bold}InstallKernelModules${normal}, but the AVD needs to be online"
    echo "	"
    echo "	${bold}AddRCscripts${normal}			install all custom *.rc scripts, placed in the rootAVD folder, into ramdisk.img/overlay.d/sbin"
    echo "	"
    echo "Options are ${bold}exclusive${normal}, only one at the time will be processed."
    echo "	"
    echo "Extra Arguments:"
    echo "	${bold}DEBUG${normal}				${bold}Debugging Mode${normal}, prevents rootAVD to pull back any patched file"
    echo "	"
    echo "	${bold}PATCHFSTAB${normal}			${bold}fstab.ranchu${normal} will get patched to automount Block Devices like ${bold}/dev/block/sda1${normal}"
    echo "					- other entries can be added in the script as well"
    echo "					- a custom build Kernel might be necessary"
    echo "	"
    echo "	${bold}GetUSBHPmodZ${normal}			The ${bold}USB HOST Permissions Module Zip${normal} will be downloaded into ${bold}/sdcard/Download${normal}"
    echo "	"
    echo "	${bold}FAKEBOOTIMG${normal}			Creates a ${bold}fake Boot.img${normal} file that can directly be patched from the ${bold}Magisk APP${normal}"
    echo "					- Magisk will be launched to patch the fake Boot.img ${bold}within 60s${normal}"
    echo "					- the fake Boot.img will be placed under ${bold}/sdcard/Download/fakeboot.img${normal}"
    echo "	"
    echo "Extra Commands can be ${bold}combined${normal}, there is no particular order."
    echo "	"
    echo "${bold}Notes: rootAVD will${normal}"
    echo "- always create ${bold}.backup${normal} files of ${bold}ramdisk.img${normal} and ${bold}kernel-ranchu${normal}"
    echo "- ${bold}replace${normal} both when done patching"
    echo "- show a ${bold}Menu${normal}, to choose the Magisk Version ${bold}(Stable || Canary, if the AVD is ${bold}online${normal}"
    echo "- make the ${bold}choosen${normal} Magisk Version to its ${bold}local${normal}"
    echo "- install all APKs placed in the Apps folder"
    FindSystemImages
    return 0
}
