#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

ROOTAVD_ROOT=$(pwd)
LIB_DIR="$ROOTAVD_ROOT/lib/rootavd"
OUT_DIR="$ROOTAVD_ROOT/dist"
OUT_FILE="$OUT_DIR/rootAVD.sh"

if [ ! -r "$LIB_DIR/bootstrap.sh" ]; then
    echo "[!] Missing bootstrap module: $LIB_DIR/bootstrap.sh" >&2
    exit 1
fi

module_has_top_level_execution() {
    awk '
        function brace_delta(line, tmp, opens, closes) {
            tmp = line
            opens = gsub(/\{/, "{", tmp)
            tmp = line
            closes = gsub(/\}/, "}", tmp)
            return opens - closes
        }
        {
            stripped = $0
            sub(/^[[:space:]]+/, "", stripped)
            if (depth == 0 && stripped ~ /^(rootavd_main|CopyMagiskToAVD|InstallMagiskToAVD)[[:space:]]+"?\$@/) {
                found = 1
            }
            depth += brace_delta($0)
            if (depth < 0) {
                depth = 0
            }
        }
        END { exit found ? 0 : 1 }
    ' "$1"
}

# shellcheck disable=SC1091
. "$LIB_DIR/bootstrap.sh"

mkdir -p "$OUT_DIR"

{
    printf '%s\n' '#!/usr/bin/env bash'
    printf '%s\n' '# shellcheck shell=bash'
    printf '%s\n' '# Bundling concatenates modules, so keep intentional module/template suppressions at bundle scope.'
    printf '%s\n' '# shellcheck disable=SC1078,SC1079,SC2004,SC2027,SC2034,SC2140'
    printf '%s\n' '##########################################################################################'
    printf '%s\n' '#'
    printf '%s\n' '# Generated rootAVD single-file bundle.'
    printf '%s\n' '# Do not edit this file directly; edit rootAVD.sh and lib/rootavd/*.sh instead.'
    printf '%s\n' '##########################################################################################'
    printf '\n'
    printf '%s\n' 'ROOTAVD_BUNDLED=true'
    printf '\n'

    module=bootstrap.sh
    module_path="$LIB_DIR/$module"
    printf '%s\n' "#################### BEGIN lib/rootavd/$module ####################"
    sed '1{/^# shellcheck shell=bash$/d;}' "$module_path"
    printf '%s\n\n' "##################### END lib/rootavd/$module #####################"

    while IFS= read -r module; do
        [ -n "$module" ] || continue
        module_path="$LIB_DIR/$module"
        if [ ! -r "$module_path" ]; then
            echo "[!] Missing module: $module_path" >&2
            exit 1
        fi
        if module_has_top_level_execution "$module_path"; then
            echo "[!] Refusing to bundle module with top-level execution: $module_path" >&2
            exit 1
        fi
        printf '%s\n' "#################### BEGIN lib/rootavd/$module ####################"
        sed '1{/^# shellcheck shell=bash$/d;}' "$module_path"
        printf '%s\n\n' "##################### END lib/rootavd/$module #####################"
    done << ROOTAVD_MODULE_LIST
$(rootavd_module_files)
ROOTAVD_MODULE_LIST

    printf '%s\n' '#################### BEGIN rootAVD.sh loader ####################'
    sed '1d' rootAVD.sh
    printf '%s\n' '##################### END rootAVD.sh loader #####################'
} > "$OUT_FILE"

chmod +x "$OUT_FILE"

bash -n "$OUT_FILE"
sh -n "$OUT_FILE"

if command -v shellcheck > /dev/null 2>&1; then
    shellcheck --severity=style "$OUT_FILE"
fi

echo "[*] Built $OUT_FILE"
